[project]
name = 'counter-radicalize'
version = '0.1.0'
description = 'Analysis of extremist rhetoric using prosody, semantics, and argument mapping.'
authors = [
    {name = 'frammenti',email = 'fra.mmenti@inventati.org'}
]
license = 'GPL-3.0'
license-files = ['LICENSE']
readme = 'README.md'
requires-python = '>=3.12,<3.14'

[tool.poetry]
packages = [{ include = 'vox_profile_release' }]

[tool.poetry.dependencies]
torch = {extras = ['audio'], version = '^2.8.0'}
torchcodec = '^0.6.0'
torchinfo = '^1.8.0'
accelerate = '^1.10.1'
transformers = '4.46.3'
datasets = '^4.0.0'
loralib = '^0.1.2'
jupyter = '^1.1.1'
ipykernel = '^6.30.1'
ipywidgets = '^8.1.7'
matplotlib = '^3.10.5'

[tool.poetry.requires-plugins]
poetry-plugin-export = '>=1.8'

